### ISSUE TITLE
[Feature] Add trackball support

### ISSUE THREAD

**Issue by kiteretro** [geebles/Super-AIO#10]
Trackball support for BB trackball

**Comment by jamesalmeida** [comment]
This would be a pretty cool feature!

**Comment by janitress** [comment]
Trackball support would be neat. I'm looking forward to some updates.

**Comment by kiteretro** [comment]
@janitress Yep it's here and it's coming ;) not far off

**Comment by jamesalmeida** [comment]
Will this feature come to Circuit Sword too?

**Comment by kiteretro** [comment]
@jamesalmeida I'll have to have a little thinking about it and the best way to support it, because on the circuit sword there aren't any free pins on the arduino.. however there are plenty on the Pi! So it should be a simple matter of adding a script on the Pi to enable support :) so yes I'll do both. I'll do this one first as I promised janitress it, and has been kind enough to send me a trackball so i have no excuse! :)
