### ISSUE TITLE
LCD reset bug

### ISSUE THREAD

**Issue by terrapinlogo** [geebles/Super-AIO#4]
Just finished (as far as I can, waiting on CeMu so have taped a pi3 to the back cover for now) and had a lot of difficulty getting the LCD to work. Initially the LCD gave a flash of white before sitting at a black screen that appeared to be just the back light. Searching in this thread found others who had a working LCD if they held the reset button for the Arduino, this got my LCD partially working but after ~30s it would fade to white. Releasing and pressing the reset button again would get it working for another short while.

I flashed the latest Arduino code from the git repo and it still had the same symptoms. Digging deeper I found the following lines in the LCD code.
`#ifdef USE_RESETPULLUP
  pinMode(RESET, INPUT_PULLUP); // Low power pullup
#else
  pinMode(RESET, INPUT);
  digitalWrite(RESET, LOW);
#endif`
Commenting out all 3 lines fixed the issue. The first line shouldn't need commenting out but I decided to leave good enough alone and haven't tested only commenting the second two lines.

**Comment by kiteretro** [comment]
![image](https://user-images.githubusercontent.com/7543492/31044556-7910b87e-a5c9-11e7-946c-6c5ea94f2684.png)
Replace R39 with a 10k 0402 resistor :) I've updated the BOM to use this resistor instead in future. Thanks for the great debugging!
