### ISSUE TITLE
X & Y on analog stick are both inverted

### ISSUE THREAD

**Issue by admarshall4** [geebles/Super-AIO#5]
Hi Kite,

I've just managed to get a 3DS XL joystick working with your first edition SAIO.

I have a problem though. In the setup script and in n64 emulation the joystick is inverted on both axes. (i.e. left makes the cursor go right, right makes it go left, up is down, down is up etc. mario kart is quite difficult like this haha) This is for the left analog stick.

What modifications can I make to the INPUT.ino file in order to correct this?
What would be the best way to fix this?

I have tried inverting the controls when setting up a controller on emulationstation to no effect.

Best regards,

Andy

**Comment by geebles** [comment]
In the config.h file this has already been taken care of:

https://github.com/geebles/Super-AIO/blob/master/source/SAIO_Arduino/SAIO_v2a/config.h#L84-L87

**Comment by admarshall4** [comment]
Thanks Geebles, I didn't see that. Much appreciated.
