### ISSUE TITLE
Dpad/Analog switch trick to play N64 on Kitana Sword Circuit

### ISSUE THREAD

**Issue by timetraveler0110** [geebles/Super-AIO#7]
Could you please make/include an Arduino trick that swaps dpad and analog so we can enjoy N64 emulation without having to insert an  analog stick in the DMG-01 desing(basicaly to keep stock appearance).
I know you can, yes , you can!
Thanks a lot Mr. Kitesurfer.

**Comment by geebles** [comment]
Hi thanks for request. I'll look in to it when I make some other changes.

As an FYI to how this will work, the DPAD will by default be a DPAD, but with a button combo (e.g. MODE + R1) the DPAD will now send input as if it were a JOYSTICK. It can be disabled with a combo (e.g. MODE + L1) and it goes back to a DPAD.

The steps to configure in ES **WHEN IT GETS IMPLEMENTED** would be:

1. Press START -> configure input
2. Press U/D/L/R etc..
3. When it gets to JOYSTICK LEFT, do MODE + R1 and then press DPAD LEFT (as this is now a joystick)
4. Repeat for the other 3 axis
5. Do MODE + L1 and finish config as normal.

**Comment by timetraveler0110** [comment]
Fabulous!

**Comment by geebles** [comment]
This issue has now been FIXED in the CIRCUIT-SWORD repo. I don't plan to implement it for the SAIO at this moment.

https://github.com/geebles/Circuit-Sword

The button combo is as follows:
```
  * R1         | DPAD IS BUTTONS ON (reset to OFF on power cycle)
  * L1         | DPAD IS BUTTONS OFF
```
